version: 2.1
orbs:
  todays-imas-idol: yutagoto/todays-imas-idol@1.0.0
jobs:
  build:
    docker:
      - image: 'ubuntu:18.04'
        environment:
          TZ: Asia/Tokyo
    steps:
      - run:
          command: |
            apt-get update
            apt-get install -y sudo
      - todays-imas-idol/slack-notification-todays-imas-idol:
          slack_username: 今日のアイドル
          slack_icon: '${SLACK_ICON}'
workflows:
  main:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
